name: TKinter

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  install_and_run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: [ '2.x', '3.8', '3.9', '3.11.0-alpha - 3.11.0', 'pypy-2.7', 'pypy-3.7', 'pypy-3.8' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }} 

      - name: Check Python version
        run: python -VV

      - run: python tkinter_test.py
     