name: TKinter

on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch:

jobs:
  install_and_run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11]
        # python-version: [ '2.x', '3.8', '3.9', '3.11.0-alpha - 3.11.0', 'pypy-2.7', 'pypy-3.7', 'pypy-3.8' ]
        python-version: [ '3.9', '3.10.1' ] # '3.11.0-alpha.3'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: |
          brew install libxext libxft
          brew reinstall tcl-tk
          ls /usr/local/Cellar/tcl-tk
          ln -s /usr/local/Cellar/tcl-tk/8.6.0/lib/libtcl8.6.dylib /usr/local/lib/libtcl8.6.dylib
          ln -s /usr/local/Cellar/tcl-tk/8.6.0/lib/libtk8.6.dylib /usr/local/lib/libtk8.6.dylib

      - name: Install Python
        # uses: actions/setup-python@v2
        uses: actions/setup-python@main
        with:
          python-version: ${{ matrix.python-version }} 

      - name: Check Python version
        run: python -VV

      - run: python tkinter_test.py
     
