name: Basic with brew uninstalled

on:
  # push:
    # branches:
    #   - master
  workflow_dispatch:

jobs:
  install_and_run:
    runs-on: [macos-11]
    steps:
      - name: Ruby info
        run: |
          whereis ruby
          ruby -v
      - name: Brew info
        run: |
          which brew
          brew config

      # - name: Find libpython3.10.dylib - Before deletion
      #   run: find / -name "libpython3.10.dylib" 2>&1 | grep -v "Permission denied" | grep -v "No such file or directory" | grep -v "Operation not permitted"

      - name: List Python content in hostedtoolcache dir - is there that lib
        run: | 
          ls -l /Users/runner/hostedtoolcache/Python/3.10.0
          ls -l /Users/runner/hostedtoolcache/Python/3.10.0/x64
          ls -l /Users/runner/hostedtoolcache/Python/3.10.0/x64/lib

      - name: List for - libintl.8.dylib
        run: |
          echo `ls /usr/local/opt/`
          echo `ls /usr/local/opt/gettext`
          echo `ls /usr/local/opt/gettext/lib/`
          echo `ls /usr/local/opt/gettext/lib/libintl.8.dylib`

      # - name: Uninstall brew
      #   run: |
      #     /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"

#      - name: Check Brew after it's uninstallation
#        run: |
#          echo "which brew: `which brew`"
#          command -v brew
#          which brew
#          brew config

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.0" # '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax

      - name: Uninstall brew
        run: |
          sudo /bin/bash ./uninstall_brew.sh --skip-cache-and-logs --path=/usr/local/Homebrew
          # /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh --skip-cache-and-logs)"
        continue-on-error: true

      - name: List Python content in hostedtoolcache dir - is there that lib
        run: | 
          ls -l /Users/runner/hostedtoolcache/Python/3.10.0
          ls -l /Users/runner/hostedtoolcache/Python/3.10.0/x64
          ls -l /Users/runner/hostedtoolcache/Python/3.10.0/x64/lib

      - name: List for - libintl.8.dylib
        run: |
          echo `ls /usr/local/opt/`
          echo `ls /usr/local/opt/gettext`
          echo `ls /usr/local/opt/gettext/lib/`
          echo `ls /usr/local/opt/gettext/lib/libintl.8.dylib`

      # - name: Find libpython3.10.dylib - After deletion
      #   run: find / -name "libpython3.10.dylib" 2>&1 | grep -v "Permission denied" | grep -v "No such file or directory" | grep -v "Operation not permitted"

      - name: Check Python version
        run: python -VV

      - run: python main.py
